name: Run python daily

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: pip install requests beautifulsoup4 openpyxl

      # 🔁 retry funkcija
      - name: Run FundNavRSDECL.py (retry 3x)
        run: |
          for i in 1 2 3; do
            echo "Attempt $i for FundNavRSDECL.py"
            python FundNavRSDECL.py && break
            echo "Failed... retrying in 60s"
            sleep 60
          done

          python FundNavRSDECL.py || exit 1

      # ✅ samo če vse uspe
      - name: Save refresh timestamp
        if: success()
        run: date +%s > last_run.txt

      - name: Commit updated CSV file
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # samo en file (kot želiš)
          [ -f FundNavRSDECL_master_history.csv ] && git add FundNavRSDECL_master_history.csv
          git add last_run.txt

          git diff --cached --quiet || git commit -m "Update fund history"
          git push
